[Redis]
Address = "127.0.0.1"
Port = 6379
Password = ""
DB = 0
Prefix = ""

[SwitchPorts]
    [SwitchPorts.sw1]
    Trunk = false
    AllowedVLANs = [1]
    Up = true

    [SwitchPorts.sw2]
    Trunk = true
    AllowedVLANs = [1]
    Up = true

    [SwitchPorts.sw3]
    Trunk = true
    AllowedVLANs = [1]
    Up = true

    [SwitchPorts.sw4]
    Trunk = true
    AllowedVLANs = [1]
    Up = false


[[ControlProcess]]
Layer = 2
Name = "Hub"
