[Redis]
Address = "127.0.0.1"
Port = 6379
Password = ""
DB = 0
Prefix = ""

[SwitchPorts]
    [SwitchPorts.sw1]
    Trunk = false
    AllowedVLANs = [1]
    Up = true

    [SwitchPorts.sw2]
    Trunk = false
    AllowedVLANs = [1]
    Up = true

    [SwitchPorts.sw3]
    Trunk = false
    AllowedVLANs = [10]
    Up = true

    [SwitchPorts.sw4]
    Trunk = false
    AllowedVLANs = [10]
    Up = true

    # [SwitchPorts."sw5.10"]
    # Trunk = false
    # AllowedVLANs = [10]
    # Up = true
    # 
    # [SwitchPorts."sw5.1"]
    # Trunk = false
    # AllowedVLANs = [1]
    # Up = true
    # 
    # [SwitchPorts.sw-mgmt]
    # Trunk = false
    # AllowedVLANs = [1]
    # Up = true

# [[ControlProcess]]
# Layer = 2
# Name = "MACFilter"
# ConfigFile = "etc/l2/MACFilter.toml"

# [[ControlProcess]]
# Layer = 2
# Name = "Hub"

[[ControlProcess]]
Layer = 2
Name = "L2Switch"

[[ControlProcess]]
Layer = 2
Name = "ARP"
ConfigFile = "etc/l2/ARPConfig.toml"

[[ControlProcess]]
Layer = 2
Name = "L2Adapter"
ConfigFile = "etc/l2/L2Adapter.toml"

[[ControlProcess]]
Layer = 3
Name = "IPv4"

[[ControlProcess]]
Layer = 3
Name = "ICMP"
ConfigFile = "etc/l3/ICMPConfig.toml"

[[ControlProcess]]
Layer = 3
Name = "Routing"
ConfigFile = "etc/l3/RoutingTable.toml"

# [[ControlProcess]]
# Layer = 3
# Name = "L3Adapter"
